baseURL = 'https://onebase-fujitsu.github.io/agile-dev-guide/'
languageCode = "ja"
hasCJKLanguage = true
title = 'Fujitsu Agile Development Guide'
theme = "book"

[params]
    BookTheme = 'light'
    BookSearch = false