baseURL = 'https://onebase-fujitsu.github.io/agile-dev-guide/'
languageCode = 'en-us'
title = 'Fujitsu Agile Development Guide'
theme = "book"

[params]
    BookSearch = true
    BookTheme = 'light'
    BookSearch = false